In [1]:
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID";
os.environ["CUDA_VISIBLE_DEVICES"]="0"; 

import pandas as pd
import numpy as np
from tqdm import *
pd.set_option('display.max_columns', None)

import random
import warnings
import math
import json
import scipy.stats as stats
from sklearn.metrics import mean_absolute_error
import matplotlib.pyplot as plt
import seaborn as sns
from collections import defaultdict
warnings.filterwarnings('ignore')

In [2]:
# # Results

# # Results From Paper Metrics

# In[2]:


import forest.benchmarking.distance_measures as dm
from scipy.spatial.distance import jensenshannon as jhn
def HellingerDistance(p, q):
    n = len(p)
    sum_ = 0.0
    for i in range(n):
        sum_ += (np.sqrt(p[i]) - np.sqrt(q[i]))**2
    result = (1.0 / np.sqrt(2.0)) * np.sqrt(sum_)
    return result


with open("Qiskit/Experiment 1 classical/results/saveRQ1.json","r") as file:
    RQ1C = json.load(file)

with open("Cirq/Experiment 1 classical/results/saveRQ1.json","r") as file:
    RQ1c = json.load(file)

with open("Rigetti/Experiment 1 classical/results/saveRQ1.json","r") as file:
    RQ1r = json.load(file)

for k in RQ1c.keys():
    RQ1C[k] = RQ1c[k]

for k in RQ1r.keys():
    RQ1C[k] = RQ1r[k]
    
with open("Q1RQ1.json","r") as file:
    nRQ1C = json.load(file)

with open("C1RQ1.json","r") as file:
    nRQ1c = json.load(file)

with open("R1RQ1.json","r") as file:
    nRQ1r = json.load(file)

for k in nRQ1c.keys():
    nRQ1C[k] = nRQ1c[k]

for k in nRQ1r.keys():
    nRQ1C[k] = nRQ1r[k]

In [3]:
# In[5]:


another = {}
programs = list(RQ1C[list(RQ1C.keys())[0]].keys())
for program in programs:
    bk_hln  = []
    bk_hlf  = []
    for bk in RQ1C.keys():
        hln = np.mean(nRQ1C[bk][program]["NoiseHL"])
        hlf = np.mean(RQ1C[bk][program]["FilterHL"])
        bk_hln.append(hln)
        bk_hlf.append(hlf)
    another[program] = {"Avg Filter HL":np.mean(bk_hlf),
                       "Avg Noise HL":np.mean(bk_hln)
                        }


# In[7]:


programs = pd.DataFrame.from_dict(another).T
programs["Improv HL"] = np.round((programs["Avg Noise HL"].values-programs["Avg Filter HL"].values)/programs["Avg Noise HL"].values*100,2)
programs[["Avg Noise HL","Avg Filter HL","Improv HL"]].to_csv("results/RQ1_Classical_HL_PP.csv")
programs[["Avg Noise HL","Avg Filter HL","Improv HL"]]

            Avg Noise HL  Avg Filter HL  Improv HL
addition        0.573654       0.593373      -3.44
ghz             0.299876       0.373849     -24.67
phase           0.313092       0.379675     -21.27
qft             0.664895       0.768990     -15.66
similarity      0.672914       0.710829      -5.63
simon           0.152828       0.249295     -63.12

In [4]:
# In[8]:


another = {}

for bk in RQ1C.keys():
    bk_tvdn = []
    bk_tvdf = []
    bk_jhnn = []
    bk_jhnf = []
    bk_hln  = []
    bk_hlf  = []
    for program in RQ1C[bk].keys():
        hln = np.mean(nRQ1C[bk][program]["NoiseHL"])
        hlf = np.mean(RQ1C[bk][program]["FilterHL"])
        bk_hln.append(hln)
        bk_hlf.append(hlf)
    another[bk.replace("Fake","")] = {
                       "Avg Filter HL":np.mean(bk_hlf),
                       "Avg Noise HL":np.mean(bk_hln)}


# In[9]:


bk_perspective = pd.DataFrame.from_dict(another).T
bk_perspective["Improv HL"] = np.round((bk_perspective["Avg Noise HL"].values-bk_perspective["Avg Filter HL"].values)/bk_perspective["Avg Noise HL"].values*100,2)
bk_perspective[["Avg Filter HL","Avg Noise HL","Improv HL"]].sort_index().round(2).to_csv("results/RQ1_Classical_HL_BP.csv")
bk_perspective[["Avg Filter HL","Avg Noise HL","Improv HL"]].sort_index().round(2)

                           Avg Filter HL  Avg Noise HL  Improv HL
9q-square                           0.59          0.66      10.64
Almaden                             0.62          0.47     -31.51
Boeblingen                          0.56          0.45     -25.19
Brooklyn                            0.49          0.40     -24.10
Cairo                               0.43          0.33     -29.27
Cambridge                           0.54          0.54       0.24
CambridgeAlternativeBasis           0.60          0.54      -9.68
Casablanca                          0.48          0.42     -15.41
Guadalupe                           0.51          0.39     -30.23
Hanoi                               0.36          0.29     -24.20
Jakarta                             0.49          0.41     -18.73
Johannesburg                        0.63          0.49     -28.64
Kolkata                             0.40          0.32     -24.28
Lagos                               0.38          0.32     -18.57
Manhattan                           0.51          0.44     -15.73
Montreal                            0.42          0.34     -23.92
Mumbai                              0.41          0.35     -18.57
Nairobi                             0.46          0.38     -21.17
Paris                               0.47          0.37     -25.39
Rochester                           0.66          0.59     -10.99
Singapore                           0.51          0.45     -13.04
Sydney                              0.45          0.36     -26.60
Toronto                             0.64          0.57     -13.04
Washington                          0.44          0.34     -29.09
rainbow                             0.61          0.68       9.40
weber                               0.67          0.70       4.61